name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache vendor
      id: cache-vendor
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-vendor

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '11.2-2022.02'

    - name: Set up QEMU
      run: sudo apt-get install --yes qemu
      
    - name: Install dependencies
      run: make deps
      
    - name: Build
      run: make

    - name: Test
      run: make test
